### ISSUE TITLE
Migration utility tracking issue

### ISSUE THREAD

**Issue by thekid** [xp-framework/test#2]
This issue tracks all TODOs for the migration utility, https://gist.github.com/thekid/ad6f908f4badbc3460a74a43e9544a86

* [x] Basic implementation
* [x] Update composer.json
* [x] Rewrite `#[Values('provider')]` to `#[Values(from: 'provider')]`
* [ ] Rewrite `#[Values(map: ...)]` to `#[Values(...)]` (converting the map!)
* [x] Rewrite `#[Expect(..., withMessage: '...')]` to `#[Expect(..., message: '...')]`
* [x] Patch .github/\*/\*.yml
* [ ] Patch azure-pipelines.yml
* [ ] Ensure annotation types are imported in a `use` statement correctly
* [x] Adjust prerequisite annotations as described in #1
* [ ] Add `#[Args]` to type if a constructor exists, see #7
* [ ] Fix global imports being stripped of first letter

**Comment by thekid** [comment]
User experience when running tests written for `xp-framework/unittest`:

![image](https://user-images.githubusercontent.com/696742/218258932-500058e6-702a-4334-ac85-94d93600f63c.png)

Should we detect this and write out an error / or maybe even run with compatibility?
